services:
  # API Gateway Service - Development Overrides
  api-gateway:
    volumes:
      - ./backend/apigateway:/app
      - /app/node_modules  # Anonymous volume to preserve node_modules
    env_file:
      - ./backend/apigateway/.env
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Auth Service - Development Overrides
  auth-service:
    volumes:
      - ./backend/AuthService:/app
      - /app/node_modules  # Anonymous volume to preserve node_modules
    env_file:
      - ./backend/AuthService/.env
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Gym Service - Development Overrides
  gym-service:
    volumes:
      - ./backend/GymService:/app
      - /app/node_modules  # Anonymous volume to preserve node_modules
    env_file:
      - ./backend/GymService/.env
    environment:
      - NODE_ENV=development
    command: npm run start  # Using start since it uses nodemon

  # Payment Service - Development Overrides
  payment-service:
    volumes:
      - ./backend/PaymentService:/app
      - /app/node_modules  # Anonymous volume to preserve node_modules
    env_file:
      - ./backend/PaymentService/.env
    environment:
      - NODE_ENV=development
    command: npm run start  # Using start since it uses nodemon

  # User Service - Development Overrides
  user-service:
    volumes:
      - ./backend/UserService:/app
      - /app/node_modules  # Anonymous volume to preserve node_modules
    env_file:
      - ./backend/UserService/.env
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Trainer Service - Development Overrides
  trainer-service:
    volumes:
      - ./backend/TrainerService:/app
      - /app/node_modules  # Anonymous volume to preserve node_modules
    env_file:
      - ./backend/TrainerService/.env
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Admin Service - Development Overrides
  admin-service:
    volumes:
      - ./backend/AdminService:/app
      - /app/node_modules  # Anonymous volume to preserve node_modules
    env_file:
      - ./backend/AdminService/.env
    environment:
      - NODE_ENV=development
    command: npm run dev
